routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();


Route::resource('user', 'UsersController');
Route::get('user/{id}', function($id){
    return User::find($id)->store; 
});

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

app/User.php
<?php

namespace App;

use App\Http\Controllers\UsersController;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone','address', 'img'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function adminlte_image()
    {
        //
    }

    public function adminlte_profile_url()
    {

        return 'user/'.\Auth::user()->id;
    }




}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $users=User::all();

        return view('admin.index', compact('users'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('admin.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        
        $this->validate($request, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => 'required|between:8,255|confirmed'
        ]);


        $entrada=$request->all();
        if($file=$request->file('img')){
            $name=$file->getClientOriginalName();
            $file->move('img',$name);
            $entrada['img']=$name;
        }
        $entrada['password']=bcrypt($request->password);

        User::create($entrada);

        return redirect("/user");

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $users=User::findOrFail($id);
        return view('admin.profile', compact('users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $users=User::findOrFail($id);
        return view('admin.edit', compact('users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $user=User::findOrFail($id);
        $inputs=$request->all();
        $this->validate($request, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255',Rule::unique('users')->ignore($user->id)],
            
        ]);

        $user->update($inputs);
               
        return redirect("/user");



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        User::findOrFail($id)->delete();
        return redirect('/user');

    }
   
    public function __construct()
    {
        $this->middleware('auth');
    }
}

resources/views/admin/create.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>Profiles</h1>
@stop
@section('auth_header', __('adminlte::adminlte.register_message'))
@section('content')

{!! Form::open(['method' => 'POST', 'action'=>'UsersController@store','files'=>true]) !!}

<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Create User</h3>
    </div>

      <div class="card-body">
          <div class="row">


                <div class="col-md-6">
                    <div class="form-group">
                        {!! Form::label('name', 'Nombre') !!}
                        {!! Form::text('name',null, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : null), 'placeholder'=> "Nombre"]) !!}
                    @if($errors->has('name'))
                        <div class="invalid-feedback">
                            <strong>El campo de nombre es obligatorio.</strong>
                        </div>
                    @endif

                    </div>
                    <div class="form-group">
                        {!! Form::label('passwrod', 'Password') !!}
                        {!! Form::password('password', ['class' => 'form-control' . ($errors->has('password') ? ' is-invalid' : null), 'placeholder'=> "Password"]) !!}
                        @if($errors->has('password'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('password') }}</strong>
                        </div>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone', 'Teléfono') !!}
                        {!! Form::text('phone',null, ['class' => 'form-control', 'placeholder'=> "Teléfono"]) !!}

                    </div>
                    <div class="form-group">
                        {!! Form::label('img', 'Foto de Perfil') !!}
                        <div class="custom-file">
                            {!! Form::file('img', old('img'),['class' => 'custom-file-input']) !!}


                          </div>


                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {!! Form::label('email', 'Email') !!}
                        {!! Form::text('email',null, ['class' => 'form-control'. ($errors->has('email') ? ' is-invalid' : null), 'placeholder'=> "Email"]) !!}
                        @if($errors->has('name'))
                        <div class="invalid-feedback">
                            <strong>El campo de Email es obligatorio.</strong>
                        </div>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('password_confirmation', 'Retrype Password') !!}
                        {!! Form::password('password_confirmation', ['class' => 'form-control'.($errors->has('password') ? ' is-invalid' : null), 'placeholder'=> "Retrype Password"]) !!}
                        @if($errors->has('name'))
                        <div class="invalid-feedback">
                            <strong>El campo es obligatorio.</strong>
                        </div>
                        @endif
                    </div>
                    <div class="form-group">
                        {!! Form::label('address', 'Dirección') !!}
                        {!! Form::text('address',null, ['class' => 'form-control', 'placeholder'=> "Dirección"]) !!}

                    </div>
                </div>
          </div>
        </div>



      <!-- /.card-body -->

      <div class="card-footer">
        {!! Form::submit('Crear Usuario', ['class'=>'btn btn-primary']) !!}
      </div>

</div>
{!! Form::close() !!}
@stop
@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/admin/edit.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>Profiles</h1>
@stop

@section('content')

{!! Form::model($users, ['method' => 'PATCH', 'action'=>['UsersController@update',$users->id]]) !!}

<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Create User</h3>
    </div>
     
      <div class="card-body">
          <div class="row">
               
                
                <div class="col-md-6">
                    <div class="form-group">
                        {!! Form::label('name', 'Nombre') !!}
                        {!! Form::text('name',null, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : null), 'placeholder'=> "Nombre"]) !!}
                    @if($errors->has('name'))
                        <div class="invalid-feedback">
                            <strong>El campo de nombre es obligatorio.</strong>
                        </div>
                    @endif
                  
                    </div> 
                   
                    <div class="form-group">
                        {!! Form::label('phone', 'Teléfono') !!}
                        {!! Form::text('phone',null, ['class' => 'form-control', 'placeholder'=> "Teléfono"]) !!}
                       
                    </div> 
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {!! Form::label('email', 'Email') !!}
                        {!! Form::text('email',null, ['class' => 'form-control'. ($errors->has('email') ? ' is-invalid' : null), 'placeholder'=> "Email"]) !!}
                        @if($errors->has('name'))
                        <div class="invalid-feedback">
                            <strong>El campo de Email es obligatorio.</strong>
                        </div>
                        @endif
                    </div> 
                    
                    <div class="form-group">
                        {!! Form::label('address', 'Dirección') !!}
                        {!! Form::text('address',null, ['class' => 'form-control', 'placeholder'=> "Dirección"]) !!}
                       
                    </div> 
                </div>
          </div>   
        </div>
      

     
      <!-- /.card-body -->

      <div class="card-footer">
        {!! Form::submit('Actualizar Usuario', ['class'=>'btn btn-primary']) !!}
      </div>
     
</div>
{!! Form::close() !!}
@stop
@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    
@stop

resources/views/admin/index.blade.php
@extends('adminlte::page')
@section('content_header')
    <h1>Profiles</h1>
@stop

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title"><b>User List</b> </h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
                <a href="{{route('user.create')}}" role="button" class="btn btn-block bg-gradient-success">Add New User</a>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0 ">
          <table class="table table-hover text-nowrap table-sm table-responsive-sm">
            <thead>
              <tr class="">
                <th>Foto</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Telefono</th>
                <th>Dirección</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
               @if ($users ?? '' )


                @foreach ($users as $user)


              <tr>
                <td > @if ($user->img)
                    <img src="/img/{{$user->img}}" class="profile-user-img img-fluid img-circle img-bordered-sm">
                    @else
                    <img src="/img/perfil.png" class="profile-user-img img-fluid img-circle">
                    @endif</td>
                <td><a href="{{route('user.show', $user->id)}}" >{{ $user->name }}</a></td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->phone }}</td>
                <td>{{ $user->address }}</td>
                <td>
                    <div class="btn-group btn-group-xs" role="group" aria-label="...">
                        {!! Form::model($user,['method'=>'DELETE', 'action'=>['UsersController@destroy',$user->id]]) !!}
                        <a class="btn btn-primary " href="{{route('user.edit', $user->id)}}"><i class="fas fa-edit"></i></a>
                        {!! Form::button('<i class="fas fa-trash"></i>', ['class'=>'btn btn-danger', 'type'=>'submit']) !!}

                        {!! Form::close() !!}
                    </div>


                </td>
            @endforeach
            @endif


                </tr>
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
@stop

resources/views/admin/profile.blade.php
@extends('adminlte::page')
@section('content_header')


<div class="row justify-content-md-center">
    <div class="col-md-6">


<div class="card card-primary card-outline">
    <div class="card-body box-profile">
      <div class="row" >
         
          
        <div class=" col-md-3 text-center">
            <img class="profile-user-img img-fluid img-circle" src="https://picsum.photos/300/300" alt="User profile picture">
            
        </div>
        <div class=" col-md-6">
        <h3 class="profile-username text-center">{{ $users->name }}</h3>
      
        <p class="text-muted text-center">{{ $users->email }}</p> 
    </div>
    </div>



     
      <div class="row justify-content-md-center">
        <div class="col-md-3">
      <strong><i class="fas fa-map-marker-alt mr-1"></i> Dirección</strong>
      <p class="text-muted">{{ $users->address}}</p>
    </div>
    <div class="col-md-3">
        <strong><i class="fas fa-map-marker-alt mr-1"></i> Teléfono</strong>
        <p class="text-muted">{{ $users->phone}}</p>
    </div>
    </div>
      <a href="{{route('user.edit', $user->id)}}" class="btn btn-primary "><b>Edit</b></a>
    </div>
    <!-- /.card-body -->
  </div>
</div>
</div>
@stop

resources/views/home.blade.php
@extends('adminlte::page')

@section('title', 'Home')

@section('content_header')
    <h1>Home</h1>
@stop

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>